version: "3.8"

services:
  redis:
    build: .
    image: redis:8.2.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "passw0rd", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"   # <-- was 8001:8001
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis-data:
