server:
  port: 6001

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:6002

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: permission
              uri: lb://permission-ms
              predicates:
                - Path=/api/permission/**
              filters:
                - TokenRelay

            - id: auth
              uri: lb://auth-ms
              predicates:
                - Path=/api/auth/**
              filters:
                - TokenRelay

            - id: frontoffice
              uri: lb://frontoffice-ms
              predicates:
                - Path=/api/frontoffice/**
              filters:
                - TokenRelay

            - id: backoffice
              uri: lb://backoffice-ms
              predicates:
                - Path=/api/backoffice/**
              filters:
                - TokenRelay

  security:
    oauth2:
      client:
        registration:
          frontoffice-app:
            provider: okta
            client-id: 0oaqp2kj9zEIU0LTy5d7
            client-secret: J21HhBvkKwJeoA2Rdb7SExC4YbRyS2fTUo3n0XLCx9yeaWKjDj_NcgpB5AgCDL4C
            scope: openid, profile, email, offline_access
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/frontoffice-app"
          backoffice-app:
            provider: okta
            client-id: 0oaqp2q4zy9xzTqE95d7
            client-secret: eSNA20W20TgxcVLAXajyvGjei7cB7S48phxmy_RIUSCh4qZNcO2UfaoXUhPqgYiS
            scope: openid, profile, email, offline_access
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/backoffice-app"
        provider:
          okta:
            issuer-uri: https://dev-50623690.okta.com/oauth2/default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost

client:
  redirect-url:
    frontoffice-app: http://localhost:4200
    backoffice-app: http://localhost:4201

app:
  oauth2:
    client-ids: frontoffice-app,backoffice-app
