server:
  port: 6001

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            # --- Auth routes per app -> auth-ms ---
            - id: frontoffice-auth
              order: 0
              uri: lb://auth-ms
              predicates:
                - Path=/api/frontoffice/auth/**
              filters:
                - TokenRelay
                - AddRequestHeader=X-App, frontoffice
                - RewritePath=/api/frontoffice/auth/(?<segment>.*), /api/auth/${segment}  # /api/frontoffice/auth/**  ->  /api/auth/**

            - id: backoffice-auth
              order: 0
              uri: lb://auth-ms
              predicates:
                - Path=/api/backoffice/auth/**
              filters:
                - TokenRelay
                - AddRequestHeader=X-App, backoffice
                - RewritePath=/api/backoffice/auth/(?<segment>.*), /api/auth/${segment}  # /api/backoffice/auth/**   ->  /api/auth/**

            # --- Business routes ---
            - id: frontoffice
              order: 1
              uri: lb://frontoffice-ms
              predicates:
                - Path=/api/frontoffice/**
              filters:
                - TokenRelay
                - name: Decide
                  args:
                    app: frontoffice

            - id: backoffice
              order: 1
              uri: lb://backoffice-ms
              predicates:
                - Path=/api/backoffice/**
              filters:
                - TokenRelay
                - name: Decide
                  args:
                    app: backoffice

            # --- Common Services routes ---
            - id: permission
              uri: lb://permission-ms
              predicates:
                - Path=/api/permission/**
              filters:
                - TokenRelay

            - id: auth
              uri: lb://auth-ms
              predicates:
                - Path=/api/auth/**
              filters:
                - TokenRelay

            - id: session
              uri: lb://session-ms
              predicates:
                - Path=/api/session/**
              filters:
                - TokenRelay

  security:
    oauth2:
      client:
        registration:
          shared-okta:
            provider: okta
            client-id: 0oar9oovewJd7YCav5d7
            client-secret: TPlUksnDr4vgeTrw1Z_394flkINBxAkDHoexCRuwbn0aW8I3YC7uxABIr8hXR-Pf
            scope: openid, profile, email, offline_access
            authorization-grant-type: authorization_code
        provider:
          okta:
            issuer-uri: https://dev-50623690.okta.com/oauth2/default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost

app:
  oauth2:
    base-registration-id: shared-okta
    default-registration-id: frontoffice-app
    apps:
      frontoffice:
        registration-id: frontoffice-app
        client-name: Frontoffice
        redirect-uri: "{baseUrl}/login/oauth2/code/frontoffice-app"
        angular-redirect: http://localhost:4200
        logout-redirect: http://localhost:4200
      backoffice:
        registration-id: backoffice-app
        client-name: Backoffice
        redirect-uri: "{baseUrl}/login/oauth2/code/backoffice-app"
        angular-redirect: http://localhost:4201
        logout-redirect: http://localhost:4201
