integration:
  auth-ms:
    base-url: http://localhost:6003/api/backoffice
  frontoffice-ms:
    base-url: http://localhost:6011/api/frontoffice
  backoffice-ms:
    base-url: http://localhost:6021/api/backoffice
  permission-ms:
    base-url: http://localhost:6004/api/permission
  session-ms:
    base-url: http://localhost:6005/api/session
  mock-external-ms:
    base-url: http://localhost:6006/api/mock-external
