server:
  port: 6003

spring:
  config:
    activate:
      on-profile: default

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-50623690.okta.com/oauth2/default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

app:
  authz:
    api:
      cache: http://localhost:6005/api/session/cache/authorizations
    mock:
      claims:
        roles:
          - ADMIN
          - USER
          - GUEST
        permissions:
          - READ
          - WRITE
          - DELETE
          - CREATE
          - UPDATE