server:
  port: 6003

spring:
  config:
    activate:
      on-profile: default

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-50623690.okta.com/oauth2/default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

app:
  clients:
    frontoffice:
      client-id: 0oaqp2kj9zEIU0LTy5d7
    backoffice:
      client-id: 0oaqp2q4zy9xzTqE95d7
