server:
  port: 6021

spring:
  config:
    activate:
      on-profile: default

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-5973406.okta.com/oauth2/default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

url:
  frontoffice:
    api:
      whoami: http://localhost:6011/api/frontoffice/whoami
