server:
  port: 6004

spring:
  config:
    activate:
      on-profile: default

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-50623690.okta.com/oauth2/default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

mock:
  permissions:
    - app: backoffice
      rules:
        - action: GET
          resource: "/api/backoffice/payments"
          roles: [ADMIN]
        - action: POST
          resource: "/api/backoffice/order"
          roles: [USER]
        - action: GET
          resource: "/api/backoffice/orders/**"
          roles:
            - USER
            - ADMIN

    - app: frontoffice
      rules:
        - action: GET
          resource: "/api/frontoffice/orders/**"
          roles: [USER]
        - action: POST
          resource: "/api/frontoffice/checkout"
          roles: [USER]