server:
  port: 6002

spring:
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:./config-repo
      fail-fast: true
